[package]
name = "mdbook-hub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5"
mdbook = "0.4"
tokio = "1.21"
tracing = "0.1"
tracing-subscriber = "0.3"
